---
services:
  katharsis:
    image: ghcr.io/hekpyto/katharsis-web:latest
    container_name: katharsis
    networks:
      - proxy
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.katharsis.entrypoints=websecure
      - traefik.http.routers.katharsis.rule=Host(`katharsis.home.tsunyanapat.com`) || Host(`kathayut.tsunyanapat.com`)
      - traefik.http.routers.katharsis.tls=true
      - traefik.http.routers.katharsis.tls.certresolver=cloudflare
      - traefik.http.services.katharsis.loadbalancer.server.port=4173
      - traefik.docker.network=proxy

networks:
  proxy:
    external: true
